---
title: "607 Week 5 Assignment"
author: "Jane Song"
date: "2025-03-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Open file

```{r}
library(dplyr)
library(tidyr)

url <- "https://raw.githubusercontent.com/j-song-npc/607-Week-5-Assignment/refs/heads/main/607%20Assignment%205.csv"

Flights <- read.csv(url, stringsAsFactors = FALSE)
```

## Clean up table
```{r}

colnames(Flights) <- c("Airline", "Status", "Los Angeles", "Phoenix", "San Diego", "San Francisco", "Seattle")

Flights <- Flights [-3,]

Flights[2, "Airline"] <- "ALASKA"
Flights[4, "Airline"] <- "AM WEST"

Flights <- Flights %>%
  mutate(across(c("Los Angeles", "Phoenix", "San Diego", "San Francisco", "Seattle"), as.character))

rownames(Flights) <- NULL

```


## Reformat into long table
``` {r}
Flights_long <- Flights %>%
  pivot_longer(cols = starts_with("Los Angeles"):starts_with("Seattle"),
               names_to = "City",
               values_to = "Count")

```


